apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ij60w8x7g-java-springboot
  janus-idp.io/tekton: ij60w8x7g-java-springboot
  backstage.io/kubernetes-id: ij60w8x7g-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ij60w8x7g-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
